K=kernel
U=user
A=arch
B=build
C=console
DSK=disk
D=drivers
FS=fs
I=include
INIT=init
LIB=lib
LNKR=linker
LCKS=locks
MM=mm
P=proc
S=sbi
SYS=syscall
T=trap

OBJS = \
	$(B)/arch/riscv/entry.o \
	$(B)/init/start.o \
	$(B)/init/test_main.o \
	$(B)/drivers/uart/uart_lite.o \
        $(B)/drivers/watchdog/soc_wdt.o \
        $(B)/sbi/legacy.o \
        $(B)/sbi/ext.o \
        $(B)/sbi/probe.o \
	$(B)/trap/kernelvec.o \
        $(B)/trap/simple_trap.o

ifndef TOOLPREFIX
TOOLPREFIX := $(shell if riscv64-unknown-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
	then echo 'riscv64-unknown-elf-'; \
	elif riscv64-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
	then echo 'riscv64-elf-'; \
	elif riscv64-none-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
	then echo 'riscv64-none-elf-'; \
	elif riscv64-linux-gnu-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
	then echo 'riscv64-linux-gnu-'; \
	elif riscv64-unknown-linux-gnu-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
	then echo 'riscv64-unknown-linux-gnu-'; \
	else echo "*** Error: Couldn't find RISC-V toolchain" 1>&2; exit 1; fi)
endif

CC = $(TOOLPREFIX)gcc
LD = $(TOOLPREFIX)ld
OBJCOPY = $(TOOLPREFIX)objcopy
OBJDUMP = $(TOOLPREFIX)objdump

CFLAGS = -Wall -Werror -Wno-unknown-attributes -O
CFLAGS += -fno-omit-frame-pointer
CFLAGS += -ggdb -gdwarf-2
CFLAGS += -march=rv64gc
CFLAGS += -mabi=lp64
CFLAGS += -std=gnu99
CFLAGS += -MD
CFLAGS += -mcmodel=medany
CFLAGS += -ffreestanding
CFLAGS += -fno-common
CFLAGS += -nostdlib
CFLAGS += -nostdinc
CFLAGS += -fno-builtin-strncpy
CFLAGS += -fno-builtin-strncmp
CFLAGS += -fno-builtin-strlen
CFLAGS += -fno-builtin-memset
CFLAGS += -fno-builtin-memmove
CFLAGS += -fno-builtin-memcmp
CFLAGS += -fno-builtin-memcpy
CFLAGS += -fno-builtin-bzero
CFLAGS += -Wno-main
CFLAGS += -Os
CFLAGS += -I$(K)/$(I)
CFLAGS += $(shell $(CC) -fno-stack-protector -E -x c /dev/null >/dev/null 2>&1 && echo -fno-stack-protector)

ifneq ($(shell $(CC) -dumpspecs 2>/dev/null | grep -e '[^f]no-pie'),)
CFLAGS += -fno-pie -no-pie
endif

ifneq ($(shell $(CC) -dumpspecs 2>/dev/null | grep -e '[^f]nopie'),)
CFLAGS += -fno-pie -nopie
endif

LDFLAGS = -z max-page-size=4096

#
# Compile C sources.
#
$(B)/%.o: $(K)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c -o $@ $<

#
# Compile assembly sources.
#
$(B)/%.o: $(K)/%.S
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c -o $@ $<

#
# Link kernel.
#
$(B)/kernel: $(OBJS) $(K)/$(LNKR)/riscv/kernel.ld
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -T $(K)/$(LNKR)/riscv/kernel.ld -o $@ $(OBJS)
	$(OBJDUMP) -S $@ > $(B)/kernel.asm
	$(OBJDUMP) -t $@ | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $(B)/kernel.sym

RV2_LOAD_ADDR = 0x11000000

#
# Create flat binary.
#
$(B)/kernel.bin: $(B)/kernel
	$(OBJCOPY) -O binary $< $@

#
# Create U-Boot image.
#
$(B)/uImage-xv6: $(B)/kernel.bin
	mkimage -A riscv -O linux -T kernel -C none \
		-a $(RV2_LOAD_ADDR) \
		-e $(RV2_LOAD_ADDR) \
		-n "xv6-minimal" \
		-d $< $@

.PHONY: rv2
rv2: $(B)/uImage-xv6

#
# Dependency files generated by -MD.
#
-include $(shell find $(B) -name '*.d' 2>/dev/null)

.PHONY: clean
clean:
	rm -rf $(B)
